# Generated by Django 3.1.5 on 2021-02-09 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cities_of_governorates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='accounts.governorates')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destrict', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('building_number', models.CharField(max_length=5)),
                ('floor', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=11)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='accounts.cities_of_governorates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
