# Generated by Django 3.1.5 on 2021-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210211_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_oreder_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_item_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
