# Generated by Django 3.1.5 on 2021-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210212_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_oreder_cost',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
